version: "2.0"

services:

  db:
    image: mysql:5.7.34
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql/ # ./mysql路径可以替换成自己的路径
      - ../../sql/:/docker-entrypoint-initdb.d/ # 初始化的脚本
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sf-admin
      MYSQL_USER: sf-admin
      MYSQL_PASSWORD: 123456

  redis:
    image: redis:alpine
    command: --requirepass "123456"
    restart: always
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai

  sfserver:
    image: qa894178522/sfmidwayadmin:stable
    restart: always
    depends_on:
      - db
      - redis
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USERNAME: sf-admin
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: sf-admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 123456
      # 可选
      MAILER_HOST: xxx
      MAILER_PORT: xxx
      MAILER_USER: xxx
      MAILER_PASS: xxx
      AMAP_KEY: xxx

  sfvue:
    image: qa894178522/sfvueadmin:midway
    restart: always
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - sfserver
    ports:
      - 7002:80
